version: 3

services:
  app:
    build: .
    volumes_from:
      - yarn-cache
    ports:
      - "5000:5000"
    networks:
      - app-network
    
  web:
    image: nginx:mainline-alpine
    container_name: web
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx:/etc/nginx/conf.d
        - web-root:/var/www/html
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - dhparam:/etc/ssl/certs
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - web
    command: certonly --webroot --webroot-path=/var/www/html --email root@multilife.live --agree-tos --no-eff-email -d multilife.live -d www.multilife.live 

  volumes:
    certbot-etc:
    certbot-var:
    web-root:

  yarn-cache:
    image: busybox
    volumes:
      - /root/.yarn-cache