version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=multilife' >> $BASH_ENV 

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Docker push
          command: |
            docker build -t jmercha/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jmercha/$IMAGE_NAME:$TAG
      - add_ssh_keys:
          fingerprints:
            - "5f:4b:4d:22:00:2b:63:3f:6b:32:14:db:03:16:9e:6f"
      - deploy:
          command: |
              scp -o "StrictHostKeyChecking=no" deploy.sh $SSH_USER@$SSH_HOST:/tmp/deploy.sh
              ssh $SSH_USER@$SSH_HOST /tmp/deploy.sh $IMAGE_NAME:$TAG