version: 2
jobs:
  build:
    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup Environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=jmercha/multilife' >> $BASH_ENV 

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn test
      - run:
          name: Docker push
          command: |
            docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $IMAGE_NAME:$TAG
            docker push $IMAGE_NAME:latest
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - add_ssh_keys:
          fingerprints:
            - "72:78:10:0a:b2:64:50:7d:c8:0d:9c:7a:10:90:f3:43"
      - run:
          command: ssh -nNT -o StrictHostKeyChecking=no -L $(pwd)/docker.sock:/var/run/docker.sock $SSH_USER@$SSH_HOST
          background: true
      - deploy:
          command: |
            docker-compose up -d -H ssh://$SSH_USER@$SSH_HOST up