# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run: yarn test

      - store_artifacts:
          path: ~/repo/dist/
          destination: dist
      
      - add_ssh_keys:
        fingerprints:
            - "41:1e:8e:f2:26:fb:3f:73:cd:bc:69:79:7a:50:85:4c"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -o "StrictHostKeyChecking=no" -o "PreferredAuthentications=publickey" package.json yarn.lock $SSH_USER@$SSH_HOST:~/dist
              scp -o "StrictHostKeyChecking=no" -o "PreferredAuthentications=publickey" -r dist $SSH_USER@$SSH_HOST:~/dist
              ssh -o "StrictHostKeyChecking=no" -o "PreferredAuthentications=publickey" $SSH_USER@$SSH_HOST cp -R ~/dist/client /var/www/multilife.live/html/ && cd ~/dist && yarn && pm2 start ~/dist/process.yml
            fi