# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run tests!
      - run: yarn test

      - store_artifacts:
          path: ~/repo/dist/
          destination: dist
      
      - add_ssh_keys:
          fingerprints:
            - "5f:4b:4d:22:00:2b:63:3f:6b:32:14:db:03:16:9e:6f"
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp -o "StrictHostKeyChecking=no" package.json yarn.lock $SSH_USER@$SSH_HOST:/home/multilife/dist
              scp -r dist $SSH_USER@$SSH_HOST:/home/multilife/dist
              ssh $SSH_USER@$SSH_HOST cd /home/multilife/dist && cp -R client/* /var/www/multilife.live/html/ && yarn && pm2 start process.yml
            fi