version: 2
jobs:
  build:

    docker:
      - image: circleci/node:13

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Setup Environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=multilife' >> $BASH_ENV 

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn test

      # Build container and deploy to prod
      - run:
          name: Docker push
          command: |
            docker build -t jmercha/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jmercha/$IMAGE_NAME:$TAG
      - add_ssh_keys:
          fingerprints:
            - "72:78:10:0a:b2:64:50:7d:c8:0d:9c:7a:10:90:f3:43"
      - deploy:
          command: |
            scp -o StrictHostKeyChecking=no deploy.sh $SSH_USER@$SSH_HOST/tmp/deploy.sh 
            ssh -t $SSH_USER@$SSH_HOST "bash -lc '/tmp/deploy.sh $IMAGE_NAME:$TAG'"